{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iggy.secretName" . }}
  labels:
    {{- include "iggy.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.iggy.rootUsername | quote }}
  password: {{ .Values.iggy.rootPassword | quote }}
{{- end }}
