apiVersion: v1
kind: Service
metadata:
  name: {{ include "iggy.fullname" . }}
  labels:
    {{- include "iggy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: tcp
      port: {{ .Values.service.tcpPort }}
      targetPort: tcp
      protocol: TCP
  selector:
    {{- include "iggy.selectorLabels" . | nindent 4 }}
